BEGIN;

-- 1. LIMPEZA PREVENTIVA (Root Cause Fix)
-- Apaga as matrizes que continham duplicações ou disciplinas em classes erradas 
-- para garantir que o INSERT abaixo recria a matriz limpa e perfeita.
DELETE FROM public.curriculum_preset_subjects 
WHERE preset_id IN ('tec_saude_enfermagem', 'tec_informatica', 'esg_puniv_cfb', 'esg_puniv_artes');

-- 2. CRIAÇÃO/ACTUALIZAÇÃO DOS PRESETS
INSERT INTO public.curriculum_presets (
    id, name, category, description, course_code, badge, recommended, class_min, class_max
)
VALUES
('esg_ciclo1','Iº Ciclo do Secundário','ESG_CICLO1','Ensino Secundário Geral','ESG','7ª-9ª',false,7,9),
('esg_puniv_artes','Artes Visuais','ESG_PUNIV','Design e Artes','AV','PUNIV',false,10,12),
('esg_puniv_cch','Ciências Humanas','ESG_PUNIV','Humanas e Línguas','CCH','PUNIV',false,10,12),
('esg_puniv_cej','Ciências Económico-Jurídicas','ESG_PUNIV','Direito e Economia','CEJ','PUNIV',false,10,12),
('esg_puniv_cfb','Ciências Físicas e Biológicas','ESG_PUNIV','Saúde e Engenharias','CFB','PUNIV',true,10,12),
('primario_generico','Ensino Primário','PRIMARIO','Base nacional (1ª-6ª)','EP','1ª-6ª',true,1,6),
('tec_comercio','Técnico de Comércio','TECNICO','Comércio e logística','COM','Técnico',false,10,13),
('tec_construcao_civil','Técnico de Construção Civil','TECNICO','Obras e edificações','CC','Técnico',false,10,13),
('tec_contabilidade','Técnico de Contabilidade','TECNICO','Contabilidade e gestão','TG','Técnico',true,10,13),
('tec_desenhador_projectista','Desenhador Projectista','TECNICO','Desenho e projeto','DP','Técnico',false,10,13),
('tec_electronica_automacao','Electrónica Industrial e Automação','TECNICO','Automação industrial','EA','Técnico',false,10,13),
('tec_electronica_telecom','Electrónica e Telecomunicações','TECNICO','Telecomunicações','ET','Técnico',false,10,13),
('tec_energia_eletrica','Técnico de Energia Eléctrica','TECNICO','Instalações eléctricas','EL','Técnico',false,10,13),
('tec_energias_renovaveis','Técnico de Energias Renováveis','TECNICO','Energia solar e eólica','ER','Técnico',false,10,13),
('tec_financas','Técnico de Finanças','TECNICO','Finanças e crédito','FIN','Técnico',false,10,13),
('tec_geologia_petroleo','Técnico de Geologia de Petróleo','TECNICO','Geologia de petróleo','GP','Técnico',false,10,13),
('tec_gestao_sistemas','Gestão de Sistemas Informáticos','TECNICO','Redes e gestão','TGS','Técnico',false,10,13),
('tec_informatica','Técnico de Informática (Hardware)','TECNICO','Hardware e suporte','TI','Técnico',false,10,13),
('tec_informatica_gestao','Técnico de Informática de Gestão','TECNICO','Informática e gestão','TIG','Técnico',true,10,13),
('tec_informatica_sistemas','Técnico de Informática (Sistemas)','TECNICO','Sistemas e redes','TIS','Técnico',false,10,13),
('tec_mecanica_manut','Técnico de Mecânica de Manutenção','TECNICO','Manutenção industrial','MEC','Técnico',false,10,13),
('tec_minas','Técnico de Minas','TECNICO','Exploração mineira','MIN','Técnico',false,10,13),
('tec_perfuracao_producao','Perfuração e Produção Petrolífera','TECNICO','Perfuração e produção','PP','Técnico',false,10,13),
('tec_producao_metalomecanica','Produção em Metalomecânica','TECNICO','Metalomecânica','PM','Técnico',false,10,13),
('tec_recursos_humanos','Técnico de Recursos Humanos','TECNICO','Gestão de pessoas','TRH','Técnico',false,10,13),
('tec_saude_analises','Técnico de Análises Clínicas','TECNICO_SAUDE','Laboratório clínico','ACL','Saúde',false,10,13),
('tec_saude_enfermagem','Técnico de Enfermagem','TECNICO_SAUDE','Cuidados de enfermagem','ENF','Saúde',false,10,13),
('tec_saude_estomatologia','Técnico de Estomatologia','TECNICO_SAUDE','Saúde oral','ESTO','Saúde',false,10,13),
('tec_saude_farmacia','Técnico de Farmácia','TECNICO_SAUDE','Farmácia e medicamentos','FARM','Saúde',false,10,13),
('tec_saude_fisioterapia','Técnico de Fisioterapia','TECNICO_SAUDE','Reabilitação e movimento','FISI','Saúde',false,10,13),
('tec_saude_nutricao','Técnico de Nutrição','TECNICO_SAUDE','Nutrição e dietética','NUTR','Saúde',false,10,13),
('tec_saude_radiologia','Técnico de Radiologia','TECNICO_SAUDE','Diagnóstico por imagem','RAD','Saúde',false,10,13),
('tec_secretariado','Técnico de Secretariado','TECNICO','Secretariado e gestão','SEC','Técnico',false,10,13)
ON CONFLICT (id) DO UPDATE SET
name = EXCLUDED.name,
category = EXCLUDED.category,
description = EXCLUDED.description,
course_code = EXCLUDED.course_code,
badge = EXCLUDED.badge,
recommended = EXCLUDED.recommended,
class_min = EXCLUDED.class_min,
class_max = EXCLUDED.class_max;

-- 3. INSERÇÃO DAS DISCIPLINAS POR PRESET (Padronizado e sem duplicações)
INSERT INTO public.curriculum_preset_subjects (
    preset_id, name, grade_level, component, weekly_hours, subject_type
)
VALUES
-- Ensino Primário
('primario_generico','Língua Portuguesa','1ª Classe','GERAL',6,'core'),
('primario_generico','Matemática','1ª Classe','GERAL',6,'core'),
('primario_generico','Estudo do Meio','1ª Classe','GERAL',4,'core'),
('primario_generico','Educação Manual e Plástica','1ª Classe','GERAL',2,'core'),
('primario_generico','Educação Física','1ª Classe','GERAL',2,'core'),
('primario_generico','Língua Portuguesa','2ª Classe','GERAL',6,'core'),
('primario_generico','Matemática','2ª Classe','GERAL',6,'core'),
('primario_generico','Estudo do Meio','2ª Classe','GERAL',4,'core'),
('primario_generico','Educação Manual e Plástica','2ª Classe','GERAL',2,'core'),
('primario_generico','Educação Física','2ª Classe','GERAL',2,'core'),
('primario_generico','Língua Portuguesa','3ª Classe','GERAL',6,'core'),
('primario_generico','Matemática','3ª Classe','GERAL',6,'core'),
('primario_generico','Estudo do Meio','3ª Classe','GERAL',4,'core'),
('primario_generico','Educação Manual e Plástica','3ª Classe','GERAL',2,'core'),
('primario_generico','Educação Física','3ª Classe','GERAL',2,'core'),
('primario_generico','Língua Portuguesa','4ª Classe','GERAL',6,'core'),
('primario_generico','Matemática','4ª Classe','GERAL',6,'core'),
('primario_generico','Estudo do Meio','4ª Classe','GERAL',4,'core'),
('primario_generico','Educação Manual e Plástica','4ª Classe','GERAL',2,'core'),
('primario_generico','Educação Física','4ª Classe','GERAL',2,'core'),
('primario_generico','Língua Portuguesa','5ª Classe','GERAL',5,'core'),
('primario_generico','Matemática','5ª Classe','GERAL',5,'core'),
('primario_generico','Ciências da Natureza','5ª Classe','GERAL',3,'core'),
('primario_generico','História e Geografia','5ª Classe','GERAL',3,'core'),
('primario_generico','Educação Moral e Cívica','5ª Classe','GERAL',1,'core'),
('primario_generico','Educação Visual e Tecnológica','5ª Classe','GERAL',2,'core'),
('primario_generico','Educação Física','5ª Classe','GERAL',2,'core'),
('primario_generico','Educação Musical','5ª Classe','GERAL',1,'core'),
('primario_generico','Língua Portuguesa','6ª Classe','GERAL',5,'core'),
('primario_generico','Matemática','6ª Classe','GERAL',5,'core'),
('primario_generico','Ciências da Natureza','6ª Classe','GERAL',3,'core'),
('primario_generico','História e Geografia','6ª Classe','GERAL',3,'core'),
('primario_generico','Educação Moral e Cívica','6ª Classe','GERAL',1,'core'),
('primario_generico','Educação Visual e Tecnológica','6ª Classe','GERAL',2,'core'),
('primario_generico','Educação Física','6ª Classe','GERAL',2,'core'),
('primario_generico','Educação Musical','6ª Classe','GERAL',1,'core'),

-- Iº Ciclo ESG
('esg_ciclo1','Língua Portuguesa','7ª Classe','GERAL',3,'core'),
('esg_ciclo1','Língua Estrangeira','7ª Classe','GERAL',3,'core'),
('esg_ciclo1','Matemática','7ª Classe','GERAL',3,'core'),
('esg_ciclo1','Biologia','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','Física','7ª Classe','GERAL',3,'core'),
('esg_ciclo1','Química','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','Geografia','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','História','7ª Classe','GERAL',3,'core'),
('esg_ciclo1','Educação Física','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Moral e Cívica','7ª Classe','GERAL',1,'core'),
('esg_ciclo1','Educação Visual e Plástica','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Laboral','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','Empreendedorismo','7ª Classe','GERAL',2,'core'),
('esg_ciclo1','Língua Portuguesa','8ª Classe','GERAL',3,'core'),
('esg_ciclo1','Língua Estrangeira','8ª Classe','GERAL',3,'core'),
('esg_ciclo1','Matemática','8ª Classe','GERAL',3,'core'),
('esg_ciclo1','Biologia','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','Física','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','Química','8ª Classe','GERAL',3,'core'),
('esg_ciclo1','Geografia','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','História','8ª Classe','GERAL',3,'core'),
('esg_ciclo1','Educação Física','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Moral e Cívica','8ª Classe','GERAL',1,'core'),
('esg_ciclo1','Educação Visual e Plástica','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Laboral','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','Empreendedorismo','8ª Classe','GERAL',2,'core'),
('esg_ciclo1','Língua Portuguesa','9ª Classe','GERAL',3,'core'),
('esg_ciclo1','Língua Estrangeira','9ª Classe','GERAL',3,'core'),
('esg_ciclo1','Matemática','9ª Classe','GERAL',3,'core'),
('esg_ciclo1','Biologia','9ª Classe','GERAL',3,'core'),
('esg_ciclo1','Física','9ª Classe','GERAL',2,'core'),
('esg_ciclo1','Química','9ª Classe','GERAL',2,'core'),
('esg_ciclo1','Geografia','9ª Classe','GERAL',3,'core'),
('esg_ciclo1','História','9ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Física','9ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Moral e Cívica','9ª Classe','GERAL',1,'core'),
('esg_ciclo1','Educação Visual e Plástica','9ª Classe','GERAL',2,'core'),
('esg_ciclo1','Educação Laboral','9ª Classe','GERAL',2,'core'),
('esg_ciclo1','Empreendedorismo','9ª Classe','GERAL',2,'core'),

-- IIº Ciclo (ESG) - Ciências Físicas e Biológicas
('esg_puniv_cfb','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cfb','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cfb','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Empreendedorismo','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cfb','Informática','10ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cfb','Física','10ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Química','10ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Biologia','10ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cfb','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cfb','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Filosofia','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Empreendedorismo','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('esg_puniv_cfb','Física','11ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Química','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cfb','Biologia','11ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Geologia','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cfb','Opção','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cfb','Língua Portuguesa','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cfb','Língua Estrangeira','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cfb','Educação Física','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Filosofia','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Empreendedorismo','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cfb','Matemática','12ª Classe','CIENTIFICA',3,'core'),
('esg_puniv_cfb','Física','12ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Química','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cfb','Biologia','12ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cfb','Geologia','12ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cfb','Opção','12ª Classe','ESPECIFICA',2,'core'),

-- IIº Ciclo (ESG) - Ciências Económico-Jurídicas
('esg_puniv_cej','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Empreendedorismo','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cej','Informática','10ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cej','Introdução ao Direito','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Introdução à Economia','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','História','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Geografia','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Filosofia','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Empreendedorismo','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cej','Informática','11ª Classe','CIENTIFICA',3,'core'),
('esg_puniv_cej','Introdução ao Direito','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Introdução à Economia','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cej','História','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Geografia','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Opção','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cej','Língua Portuguesa','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Língua Estrangeira','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Educação Física','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Filosofia','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Empreendedorismo','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cej','Formação de Atitudes Integradoras','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cej','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cej','Informática','12ª Classe','CIENTIFICA',3,'core'),
('esg_puniv_cej','Introdução ao Direito','12ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cej','Introdução à Economia','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','História','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Geografia','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cej','Desenvolvimento Económico e Social','12ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cej','Opção','12ª Classe','ESPECIFICA',2,'core'),

-- IIº Ciclo (ESG) - Ciências Humanas
('esg_puniv_cch','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',4,'core'),
('esg_puniv_cch','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cch','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Empreendedorismo','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('esg_puniv_cch','Informática','10ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_cch','Língua Estrangeira II','10ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cch','História','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cch','Geografia','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cch','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',4,'core'),
('esg_puniv_cch','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cch','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Filosofia','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Empreendedorismo','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Matemática','11ª Classe','CIENTIFICA',2,'core'),
('esg_puniv_cch','Língua Estrangeira II','11ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cch','História','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cch','Geografia','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cch','Literatura','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cch','Opção','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cch','Língua Portuguesa','12ª Classe','SOCIO_CULTURAL',4,'core'),
('esg_puniv_cch','Língua Estrangeira','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_cch','Educação Física','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Filosofia','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Empreendedorismo','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_cch','Língua Estrangeira II','12ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_cch','História','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cch','Geografia','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_cch','Matemática','12ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cch','Literatura','12ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_cch','Opção','12ª Classe','ESPECIFICA',2,'core'),

-- IIº Ciclo (ESG) - Artes Visuais
('esg_puniv_artes','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',4,'core'),
('esg_puniv_artes','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_artes','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Empreendedorismo','10ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('esg_puniv_artes','Informática','10ª Classe','CIENTIFICA',4,'core'),
('esg_puniv_artes','Desenho','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','Geometria Descritiva','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','História das Artes','10ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_artes','Técnica de Expressão Artística','10ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_artes','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_artes','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Filosofia','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Empreendedorismo','11ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Desenho','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','Teoria e Prática do Design','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','Geometria Descritiva','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','História das Artes','11ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','Técnica de Expressão Artística','11ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_artes','Opção','11ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_artes','Língua Portuguesa','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_artes','Língua Estrangeira','12ª Classe','SOCIO_CULTURAL',3,'core'),
('esg_puniv_artes','Educação Física','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Filosofia','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Empreendedorismo','12ª Classe','SOCIO_CULTURAL',2,'core'),
('esg_puniv_artes','Desenho','12ª Classe','ESPECIFICA',2,'core'),
('esg_puniv_artes','Teoria e Prática do Design','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','História das Artes','12ª Classe','ESPECIFICA',3,'core'),
('esg_puniv_artes','Técnica de Expressão Artística','12ª Classe','ESPECIFICA',4,'core'),
('esg_puniv_artes','Opção','12ª Classe','ESPECIFICA',2,'core'),

-- Técnico de Contabilidade
('tec_contabilidade','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_contabilidade','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_contabilidade','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_contabilidade','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_contabilidade','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_contabilidade','Sociologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_contabilidade','Informática Aplicada à Contabilidade','10ª Classe','CIENTIFICA',4,'core'),
('tec_contabilidade','Contabilidade Financeira','10ª Classe','TECNICA',4,'core'),
('tec_contabilidade','Administração de Empresas','10ª Classe','TECNICA',3,'core'),
('tec_contabilidade','Documentação e Legislação Comercial','10ª Classe','TECNICA',3,'core'),
('tec_contabilidade','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_contabilidade','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_contabilidade','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_contabilidade','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_contabilidade','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_contabilidade','Informática Aplicada à Contabilidade','11ª Classe','CIENTIFICA',4,'core'),
('tec_contabilidade','Contabilidade Financeira','11ª Classe','TECNICA',5,'core'),
('tec_contabilidade','Técnica de Cálculo e Estatística','11ª Classe','TECNICA',3,'core'),
('tec_contabilidade','Administração de Empresas','11ª Classe','TECNICA',3,'core'),
('tec_contabilidade','Documentação e Legislação Fiscal','11ª Classe','TECNICA',3,'core'),
('tec_contabilidade','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_contabilidade','Direito','12ª Classe','CIENTIFICA',3,'core'),
('tec_contabilidade','Economia','12ª Classe','CIENTIFICA',3,'core'),
('tec_contabilidade','Contabilidade Financeira','12ª Classe','TECNICA',5,'core'),
('tec_contabilidade','Contabilidade Analítica','12ª Classe','TECNICA',6,'core'),
('tec_contabilidade','Análise Económica e Financeira','12ª Classe','TECNICA',4,'core'),
('tec_contabilidade','Projecto Tecnológico','12ª Classe','TECNICA',6,'projeto'),
('tec_contabilidade','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_contabilidade','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Informática de Gestão
('tec_informatica_gestao','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_gestao','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_gestao','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_gestao','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_gestao','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_gestao','Base de Dados','10ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_gestao','Organização e Administração de Empresas','10ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Técnicas e Linguagens de Programação','10ª Classe','TECNICA',6,'core'),
('tec_informatica_gestao','Tecnologias de Informação e de Comunicação','10ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_gestao','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_gestao','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_gestao','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_gestao','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_gestao','Noções de Direito','11ª Classe','CIENTIFICA',3,'core'),
('tec_informatica_gestao','Organização e Administração de Empresas','11ª Classe','TECNICA',3,'core'),
('tec_informatica_gestao','Redes de Computadores','11ª Classe','TECNICA',3,'core'),
('tec_informatica_gestao','Técnicas e Linguagens de Programação','11ª Classe','TECNICA',3,'core'),
('tec_informatica_gestao','Tecnologias de Informação e de Comunicação','11ª Classe','TECNICA',3,'core'),
('tec_informatica_gestao','Informática Aplicada à Gestão','11ª Classe','TECNICA',3,'core'),
('tec_informatica_gestao','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_gestao','Empreendedorismo','12ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Organização e Administração de Empresas','12ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Técnicas e Linguagens de Programação','12ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Tecnologias de Informação e de Comunicação','12ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Informática Aplicada à Gestão','12ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Sistema de Informação','12ª Classe','TECNICA',4,'core'),
('tec_informatica_gestao','Instalação e Manutenção de Equipamentos Informáticos','12ª Classe','TECNICA',2,'core'),
('tec_informatica_gestao','Projecto Tecnológico','12ª Classe','TECNICA',2,'projeto'),
('tec_informatica_gestao','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_informatica_gestao','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Recursos Humanos
('tec_recursos_humanos','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_recursos_humanos','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_recursos_humanos','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_recursos_humanos','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_recursos_humanos','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('tec_recursos_humanos','Introdução à Economia','10ª Classe','CIENTIFICA',3,'core'),
('tec_recursos_humanos','Sociologia das Organizações','10ª Classe','CIENTIFICA',3,'core'),
('tec_recursos_humanos','Empreendedorismo','10ª Classe','CIENTIFICA',2,'core'),
('tec_recursos_humanos','Informática de Gestão','10ª Classe','CIENTIFICA',2,'core'),
('tec_recursos_humanos','Formação e Desenvolvimento do Pessoal','10ª Classe','TECNICA',3,'core'),
('tec_recursos_humanos','Teoria da Administração e do Trabalho','10ª Classe','TECNICA',3,'core'),
('tec_recursos_humanos','Sistema de Comunicação e Informação em Recursos Humanos','10ª Classe','TECNICA',2,'core'),
('tec_recursos_humanos','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_recursos_humanos','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_recursos_humanos','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_recursos_humanos','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_recursos_humanos','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_recursos_humanos','Direito e Legislação Social e do Trabalho','11ª Classe','CIENTIFICA',3,'core'),
('tec_recursos_humanos','Empreendedorismo','11ª Classe','CIENTIFICA',2,'core'),
('tec_recursos_humanos','Informática de Gestão','11ª Classe','CIENTIFICA',2,'core'),
('tec_recursos_humanos','Formação e Desenvolvimento do Pessoal','11ª Classe','TECNICA',3,'core'),
('tec_recursos_humanos','Teoria da Administração e do Trabalho','11ª Classe','TECNICA',3,'core'),
('tec_recursos_humanos','Sistema de Comunicação e Informação em Recursos Humanos','11ª Classe','TECNICA',2,'core'),
('tec_recursos_humanos','Planeamento e Análise de Funções','11ª Classe','TECNICA',3,'core'),
('tec_recursos_humanos','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_recursos_humanos','Psicologia Social e do Trabalho','12ª Classe','CIENTIFICA',4,'core'),
('tec_recursos_humanos','Empreendedorismo','12ª Classe','CIENTIFICA',2,'core'),
('tec_recursos_humanos','Formação e Desenvolvimento do Pessoal','12ª Classe','TECNICA',4,'core'),
('tec_recursos_humanos','Teoria da Administração e do Trabalho','12ª Classe','TECNICA',4,'core'),
('tec_recursos_humanos','Planeamento e Análise de Funções','12ª Classe','TECNICA',4,'core'),
('tec_recursos_humanos','Rotina de Trabalho','12ª Classe','TECNICA',3,'core'),
('tec_recursos_humanos','Organização e Gestão de Recursos Humanos','12ª Classe','TECNICA',4,'core'),
('tec_recursos_humanos','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_recursos_humanos','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_recursos_humanos','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Secretariado
('tec_secretariado','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_secretariado','Francês','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_secretariado','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_secretariado','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_secretariado','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('tec_secretariado','Inglês','10ª Classe','CIENTIFICA',3,'core'),
('tec_secretariado','Economia','10ª Classe','CIENTIFICA',3,'core'),
('tec_secretariado','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_secretariado','Contabilidade Empresarial','10ª Classe','TECNICA',3,'core'),
('tec_secretariado','Prática de Secretariado','10ª Classe','TECNICA',4,'core'),
('tec_secretariado','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_secretariado','Francês','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_secretariado','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_secretariado','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_secretariado','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_secretariado','Inglês','11ª Classe','CIENTIFICA',3,'core'),
('tec_secretariado','Psicologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_secretariado','Informática','11ª Classe','CIENTIFICA',2,'core'),
('tec_secretariado','Contabilidade Empresarial','11ª Classe','TECNICA',4,'core'),
('tec_secretariado','Documentação e Legislação Comercial, Laboral e Fiscal','11ª Classe','TECNICA',3,'core'),
('tec_secretariado','Prática de Secretariado','11ª Classe','TECNICA',4,'core'),
('tec_secretariado','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_secretariado','Psicologia','12ª Classe','CIENTIFICA',3,'core'),
('tec_secretariado','Informática','12ª Classe','CIENTIFICA',2,'core'),
('tec_secretariado','Técnica de Cálculo e Estatística','12ª Classe','TECNICA',3,'core'),
('tec_secretariado','Documentação e Legislação Comercial, Laboral e Fiscal','12ª Classe','TECNICA',3,'core'),
('tec_secretariado','Prática de Secretariado','12ª Classe','TECNICA',5,'core'),
('tec_secretariado','Português Técnico','12ª Classe','TECNICA',3,'core'),
('tec_secretariado','Inglês Técnico','12ª Classe','TECNICA',3,'core'),
('tec_secretariado','Francês Técnico','12ª Classe','TECNICA',3,'core'),
('tec_secretariado','Projecto Tecnológico','12ª Classe','TECNICA',6,'projeto'),
('tec_secretariado','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_secretariado','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Finanças
('tec_financas','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_financas','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_financas','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_financas','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_financas','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('tec_financas','Introdução à Economia','10ª Classe','CIENTIFICA',4,'core'),
('tec_financas','Informática de Gestão','10ª Classe','CIENTIFICA',2,'core'),
('tec_financas','Contabilidade Financeira','10ª Classe','TECNICA',4,'core'),
('tec_financas','Documentação e Legislação Comercial','10ª Classe','TECNICA',4,'core'),
('tec_financas','Análise de Crédito, Financiamento e Investimento','10ª Classe','TECNICA',4,'core'),
('tec_financas','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_financas','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_financas','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_financas','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_financas','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_financas','Direito Económico','11ª Classe','CIENTIFICA',2,'core'),
('tec_financas','Informática de Gestão','11ª Classe','CIENTIFICA',2,'core'),
('tec_financas','Contabilidade Financeira','11ª Classe','TECNICA',4,'core'),
('tec_financas','Organização e Gestão de Empresas Financeiras','11ª Classe','TECNICA',2,'core'),
('tec_financas','Técnicas de Recepção, Atendimento e Cobrança','11ª Classe','TECNICA',4,'core'),
('tec_financas','Análise de Crédito, Financiamento e Investimento','11ª Classe','TECNICA',4,'core'),
('tec_financas','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_financas','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_financas','Organização e Gestão de Empresas Financeiras','12ª Classe','TECNICA',3,'core'),
('tec_financas','Processos Financeiros Orçamentários','12ª Classe','TECNICA',3,'core'),
('tec_financas','Legislação Contabilística Tributários','12ª Classe','TECNICA',3,'core'),
('tec_financas','Análise de Crédito, Financiamento e Investimento','12ª Classe','TECNICA',3,'core'),
('tec_financas','Mercado de Capitais e Bolsas de Valores','12ª Classe','TECNICA',4,'core'),
('tec_financas','Análise Económica e Financeira da Empresa','12ª Classe','TECNICA',4,'core'),
('tec_financas','Contabilidade Bancária','12ª Classe','TECNICA',4,'core'),
('tec_financas','Projecto Tecnológico','12ª Classe','TECNICA',2,'projeto'),
('tec_financas','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_financas','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Comércio
('tec_comercio','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_comercio','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_comercio','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_comercio','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_comercio','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('tec_comercio','Introdução à Economia','10ª Classe','CIENTIFICA',4,'core'),
('tec_comercio','Geografia Económica','10ª Classe','CIENTIFICA',3,'core'),
('tec_comercio','Informática de Gestão','10ª Classe','CIENTIFICA',2,'core'),
('tec_comercio','Contabilidade Comercial','10ª Classe','TECNICA',4,'core'),
('tec_comercio','Higiene e Segurança Alimentar','10ª Classe','TECNICA',2,'core'),
('tec_comercio','Gestão de Aprovisionamento','10ª Classe','TECNICA',3,'core'),
('tec_comercio','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_comercio','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_comercio','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_comercio','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_comercio','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_comercio','Noções de Direito Económico','11ª Classe','CIENTIFICA',3,'core'),
('tec_comercio','Psicologia do Consumidor','11ª Classe','CIENTIFICA',3,'core'),
('tec_comercio','Informática de Gestão','11ª Classe','CIENTIFICA',2,'core'),
('tec_comercio','Contabilidade Comercial','11ª Classe','TECNICA',4,'core'),
('tec_comercio','Documentação e Legislação Comercial','11ª Classe','TECNICA',3,'core'),
('tec_comercio','Gestão da Cadeia de Fornecedores','11ª Classe','TECNICA',3,'core'),
('tec_comercio','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_comercio','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_comercio','Organização e Gestão de Empresas Comerciais','12ª Classe','TECNICA',4,'core'),
('tec_comercio','Comércio Internacional','12ª Classe','TECNICA',3,'core'),
('tec_comercio','Técnicas de Negociação e Vendas','12ª Classe','TECNICA',3,'core'),
('tec_comercio','Protecção e Defesa do Consumidor','12ª Classe','TECNICA',3,'core'),
('tec_comercio','Custos Associados à Gestão de Stok','12ª Classe','TECNICA',4,'core'),
('tec_comercio','Fiscalidade','12ª Classe','TECNICA',3,'core'),
('tec_comercio','Contabilidade de Custo','12ª Classe','TECNICA',4,'core'),
('tec_comercio','Projecto Tecnológico','12ª Classe','TECNICA',2,'projeto'),
('tec_comercio','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_comercio','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Construção Civil
('tec_construcao_civil','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_construcao_civil','Língua Inglesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_construcao_civil','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_construcao_civil','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_construcao_civil','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_construcao_civil','Física','10ª Classe','CIENTIFICA',4,'core'),
('tec_construcao_civil','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_construcao_civil','Desenho Técnico','10ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Materiais de Construção','10ª Classe','TECNICA',3,'core'),
('tec_construcao_civil','Topografia','10ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Práticas Oficinais (Pedreiro)','10ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_construcao_civil','Língua Inglesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_construcao_civil','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_construcao_civil','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_construcao_civil','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_construcao_civil','Física','11ª Classe','CIENTIFICA',3,'core'),
('tec_construcao_civil','Estabilidade e Betão Armado','11ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Construção de Edifícios','11ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Desenho de Construção','11ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Topografia','11ª Classe','TECNICA',3,'core'),
('tec_construcao_civil','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_construcao_civil','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_construcao_civil','Medições e Orçamentos','12ª Classe','TECNICA',4,'core'),
('tec_construcao_civil','Org. e Gestão de Obras','12ª Classe','TECNICA',3,'core'),
('tec_construcao_civil','Instalações Prediais (Água/Luz)','12ª Classe','TECNICA',3,'core'),
('tec_construcao_civil','Higiene e Segurança no Trabalho','12ª Classe','TECNICA',2,'core'),
('tec_construcao_civil','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_construcao_civil','Língua Portuguesa','12ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_construcao_civil','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_construcao_civil','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Energia Eléctrica
('tec_energia_eletrica','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_energia_eletrica','Língua Inglesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_energia_eletrica','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_energia_eletrica','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_energia_eletrica','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_energia_eletrica','Física','10ª Classe','CIENTIFICA',4,'core'),
('tec_energia_eletrica','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_energia_eletrica','Electrotecnia','10ª Classe','TECNICA',4,'core'),
('tec_energia_eletrica','Desenho Esquemático','10ª Classe','TECNICA',3,'core'),
('tec_energia_eletrica','Tecnologia Eléctrica','10ª Classe','TECNICA',3,'core'),
('tec_energia_eletrica','Práticas Oficinais','10ª Classe','TECNICA',5,'core'),
('tec_energia_eletrica','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_energia_eletrica','Língua Inglesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_energia_eletrica','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_energia_eletrica','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_energia_eletrica','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_energia_eletrica','Física','11ª Classe','CIENTIFICA',3,'core'),
('tec_energia_eletrica','Máquinas Eléctricas','11ª Classe','TECNICA',4,'core'),
('tec_energia_eletrica','Instalações Eléctricas','11ª Classe','TECNICA',4,'core'),
('tec_energia_eletrica','Electrotecnia','11ª Classe','TECNICA',3,'core'),
('tec_energia_eletrica','Práticas Oficinais','11ª Classe','TECNICA',5,'core'),
('tec_energia_eletrica','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_energia_eletrica','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_energia_eletrica','Automatismos Industriais','12ª Classe','TECNICA',4,'core'),
('tec_energia_eletrica','Redes de Energia','12ª Classe','TECNICA',3,'core'),
('tec_energia_eletrica','Electrónica Industrial','12ª Classe','TECNICA',3,'core'),
('tec_energia_eletrica','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_energia_eletrica','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_energia_eletrica','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Mecânica de Manutenção
('tec_mecanica_manut','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_mecanica_manut','Língua Inglesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_mecanica_manut','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_mecanica_manut','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_mecanica_manut','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_mecanica_manut','Física','10ª Classe','CIENTIFICA',4,'core'),
('tec_mecanica_manut','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_mecanica_manut','Tecnologia Mecânica','10ª Classe','TECNICA',4,'core'),
('tec_mecanica_manut','Desenho Técnico','10ª Classe','TECNICA',4,'core'),
('tec_mecanica_manut','Práticas Oficinais','10ª Classe','TECNICA',6,'core'),
('tec_mecanica_manut','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_mecanica_manut','Língua Inglesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_mecanica_manut','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_mecanica_manut','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_mecanica_manut','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_mecanica_manut','Física','11ª Classe','CIENTIFICA',3,'core'),
('tec_mecanica_manut','Órgãos de Máquinas','11ª Classe','TECNICA',3,'core'),
('tec_mecanica_manut','Tecnologia Mecânica','11ª Classe','TECNICA',4,'core'),
('tec_mecanica_manut','Desenho de Construções Mecânicas','11ª Classe','TECNICA',3,'core'),
('tec_mecanica_manut','Práticas Oficinais','11ª Classe','TECNICA',6,'core'),
('tec_mecanica_manut','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_mecanica_manut','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_mecanica_manut','Tecnologia de Manutenção','12ª Classe','TECNICA',4,'core'),
('tec_mecanica_manut','Hidráulica e Pneumática','12ª Classe','TECNICA',4,'core'),
('tec_mecanica_manut','Comando Numérico (CNC)','12ª Classe','TECNICA',3,'core'),
('tec_mecanica_manut','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_mecanica_manut','Língua Portuguesa','12ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_mecanica_manut','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_mecanica_manut','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Técnico de Informática (Sistemas)
('tec_informatica_sistemas','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_sistemas','Língua Inglesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_sistemas','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_sistemas','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_sistemas','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_informatica_sistemas','Física','10ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_sistemas','Electrotecnia','10ª Classe','TECNICA',3,'core'),
('tec_informatica_sistemas','Técnicas e Linguagens de Programação','10ª Classe','TECNICA',6,'core'),
('tec_informatica_sistemas','Sistemas de Exploração e Arquitectura de Computadores','10ª Classe','TECNICA',3,'core'),
('tec_informatica_sistemas','Tecnologias de Informação e de Comunicação','10ª Classe','TECNICA',3,'core'),
('tec_informatica_sistemas','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_sistemas','Língua Inglesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica_sistemas','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_sistemas','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica_sistemas','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_sistemas','Física','11ª Classe','CIENTIFICA',3,'core'),
('tec_informatica_sistemas','Técnicas e Linguagens de Programação','11ª Classe','TECNICA',5,'core'),
('tec_informatica_sistemas','Redes Informáticas','11ª Classe','TECNICA',3,'core'),
('tec_informatica_sistemas','Sistemas de Exploração e Arquitectura de Computadores','11ª Classe','TECNICA',4,'core'),
('tec_informatica_sistemas','Bases de Dados','11ª Classe','TECNICA',3,'core'),
('tec_informatica_sistemas','Matemática','12ª Classe','CIENTIFICA',4,'core'),
('tec_informatica_sistemas','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_informatica_sistemas','Técnicas e Linguagens de Programação','12ª Classe','TECNICA',5,'core'),
('tec_informatica_sistemas','Redes Informáticas','12ª Classe','TECNICA',4,'core'),
('tec_informatica_sistemas','Administração de Sistemas de Informação','12ª Classe','TECNICA',3,'core'),
('tec_informatica_sistemas','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_informatica_sistemas','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_informatica_sistemas','Estágio Curricular','13ª Classe','TECNICA',20,'projeto'),

-- Desenhador Projectista
('tec_desenhador_projectista','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_desenhador_projectista','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_desenhador_projectista','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_desenhador_projectista','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_desenhador_projectista','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_desenhador_projectista','Física','10ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Química','10ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Geometria Descritiva','10ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Empreendedorismo','10ª Classe','TECNICA',2,'core'),
('tec_desenhador_projectista','Desenho de Projecto','10ª Classe','TECNICA',3,'core'),
('tec_desenhador_projectista','Técnicas de Construção Civil','10ª Classe','TECNICA',3,'core'),
('tec_desenhador_projectista','Informática Aplicada','10ª Classe','TECNICA',3,'core'),
('tec_desenhador_projectista','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_desenhador_projectista','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_desenhador_projectista','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_desenhador_projectista','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_desenhador_projectista','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_desenhador_projectista','Física','11ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Química','11ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Geometria Descritiva','11ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Empreendedorismo','11ª Classe','TECNICA',2,'core'),
('tec_desenhador_projectista','Desenho de Projecto','11ª Classe','TECNICA',4,'core'),
('tec_desenhador_projectista','Técnicas de Construção Civil','11ª Classe','TECNICA',3,'core'),
('tec_desenhador_projectista','Informática Aplicada','11ª Classe','TECNICA',3,'core'),
('tec_desenhador_projectista','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_desenhador_projectista','Física','12ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Organização e Gestão Industrial','12ª Classe','CIENTIFICA',2,'core'),
('tec_desenhador_projectista','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_desenhador_projectista','Desenho de Projecto','12ª Classe','TECNICA',4,'core'),
('tec_desenhador_projectista','Técnicas de Construção Civil','12ª Classe','TECNICA',5,'core'),
('tec_desenhador_projectista','Técnicas de Medições e Orçamentos','12ª Classe','TECNICA',4,'core'),
('tec_desenhador_projectista','Informática Aplicada','12ª Classe','TECNICA',4,'core'),
('tec_desenhador_projectista','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_desenhador_projectista','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_desenhador_projectista','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Electrónica e Telecomunicações
('tec_electronica_telecom','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_electronica_telecom','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_electronica_telecom','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_electronica_telecom','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_electronica_telecom','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_electronica_telecom','Física','10ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Química','10ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Empreendedorismo','10ª Classe','TECNICA',2,'core'),
('tec_electronica_telecom','Electricidade e Electrónica','10ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Tecnologias das Telecomunicações','10ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Prática Oficinal','10ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_electronica_telecom','Física','11ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Química','11ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Empreendedorismo','11ª Classe','TECNICA',2,'core'),
('tec_electronica_telecom','Desenho Técnico','11ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Electricidade e Electrónica','11ª Classe','TECNICA',2,'core'),
('tec_electronica_telecom','Sistemas Digitais','11ª Classe','TECNICA',2,'core'),
('tec_electronica_telecom','Tecnologias das Telecomunicações','11ª Classe','TECNICA',2,'core'),
('tec_electronica_telecom','Prática Oficinal','11ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_electronica_telecom','Física','12ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Organização e Gestão Industrial','12ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_telecom','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_electronica_telecom','Electricidade e Electrónica','12ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Sistemas Digitais','12ª Classe','TECNICA',4,'core'),
('tec_electronica_telecom','Telecomunicações','12ª Classe','TECNICA',4,'core'),
('tec_electronica_telecom','Tecnologias das Telecomunicações','12ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Prática Oficinal','12ª Classe','TECNICA',3,'core'),
('tec_electronica_telecom','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_electronica_telecom','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_electronica_telecom','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Electrónica Industrial e Automação
('tec_electronica_automacao','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_electronica_automacao','Física','10ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_automacao','Química','10ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_automacao','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_electronica_automacao','Electricidade e Electrónica','10ª Classe','TECNICA',3,'core'),
('tec_electronica_automacao','Tecnologias de Comando','10ª Classe','TECNICA',3,'core'),
('tec_electronica_automacao','Práticas Oficinais','10ª Classe','TECNICA',3,'core'),
('tec_electronica_automacao','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_electronica_automacao','Desenho Técnico','11ª Classe','TECNICA',3,'core'),
('tec_electronica_automacao','Electricidade e Electrónica','11ª Classe','TECNICA',2,'core'),
('tec_electronica_automacao','Sistemas Digitais','11ª Classe','TECNICA',2,'core'),
('tec_electronica_automacao','Tecnologias de Comando','11ª Classe','TECNICA',2,'core'),
('tec_electronica_automacao','Práticas Oficinais','11ª Classe','TECNICA',3,'core'),
('tec_electronica_automacao','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_electronica_automacao','Electricidade e Electrónica','12ª Classe','TECNICA',5,'core'),
('tec_electronica_automacao','Sistemas Digitais','12ª Classe','TECNICA',4,'core'),
('tec_electronica_automacao','Máquinas Eléctricas','12ª Classe','TECNICA',4,'core'),
('tec_electronica_automacao','Tecnologias de Comando','12ª Classe','TECNICA',4,'core'),
('tec_electronica_automacao','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_electronica_automacao','Projecto Tecnológico','13ª Classe','TECNICA',8,'core'),
('tec_electronica_automacao','Estágio Curricular','13ª Classe','TECNICA',20,'core'),

-- Técnico de Energias Renováveis
('tec_energias_renovaveis','Matemática','10ª Classe','CIENTIFICA',4,'core'),
('tec_energias_renovaveis','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_energias_renovaveis','Química','10ª Classe','CIENTIFICA',2,'core'),
('tec_energias_renovaveis','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_energias_renovaveis','Desenho Técnico','10ª Classe','TECNICA',2,'core'),
('tec_energias_renovaveis','Electricidade e Electrónica','10ª Classe','TECNICA',2,'core'),
('tec_energias_renovaveis','Tecnologias e Processos','10ª Classe','TECNICA',2,'core'),
('tec_energias_renovaveis','Práticas Oficinais','10ª Classe','TECNICA',3,'core'),
('tec_energias_renovaveis','Matemática','11ª Classe','CIENTIFICA',5,'core'),
('tec_energias_renovaveis','Electricidade e Electrónica','11ª Classe','TECNICA',3,'core'),
('tec_energias_renovaveis','Tecnologias e Processos','11ª Classe','TECNICA',3,'core'),
('tec_energias_renovaveis','Práticas Oficinais','11ª Classe','TECNICA',3,'core'),
('tec_energias_renovaveis','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_energias_renovaveis','Desenho Técnico','12ª Classe','TECNICA',4,'core'),
('tec_energias_renovaveis','Tecnologias e Processos','12ª Classe','TECNICA',5,'core'),
('tec_energias_renovaveis','Práticas Oficinais','12ª Classe','TECNICA',6,'core'),
('tec_energias_renovaveis','Eficiência Energética','12ª Classe','TECNICA',2,'core'),
('tec_energias_renovaveis','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_energias_renovaveis','Projecto Tecnológico','13ª Classe','TECNICA',8,'core'),
('tec_energias_renovaveis','Estágio Curricular','13ª Classe','TECNICA',20,'core'),

-- Técnico de Geologia de Petróleo
('tec_geologia_petroleo','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_geologia_petroleo','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_geologia_petroleo','Química','10ª Classe','CIENTIFICA',3,'core'),
('tec_geologia_petroleo','Introdução à Indústria de Petróleos','10ª Classe','TECNICA',4,'core'),
('tec_geologia_petroleo','Geologia Geral','10ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Desenho Técnico','10ª Classe','TECNICA',4,'core'),
('tec_geologia_petroleo','Mineralogia e Petrologia','10ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Geologia Estrutural e Estratigráfica','10ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_geologia_petroleo','Geofísica','11ª Classe','TECNICA',4,'core'),
('tec_geologia_petroleo','Saúde, Segurança e Ambiente','11ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Inglês Técnico','11ª Classe','TECNICA',2,'core'),
('tec_geologia_petroleo','Mineralogia e Petrologia','11ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Geologia dos Hidrocarbonetos','12ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Geologia de Sonda','12ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Técnicas de Laboratório','12ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Topografia','12ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Geofísica','12ª Classe','TECNICA',3,'core'),
('tec_geologia_petroleo','Trabalhos de Campo','13ª Classe','TECNICA',8,'core'),
('tec_geologia_petroleo','Projecto Tecnológico','13ª Classe','TECNICA',8,'core'),
('tec_geologia_petroleo','Estágio Curricular','13ª Classe','TECNICA',20,'core'),

-- Técnico de Perfuração e Produção Petrolífera
('tec_perfuracao_producao','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_perfuracao_producao','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_perfuracao_producao','Química','10ª Classe','CIENTIFICA',3,'core'),
('tec_perfuracao_producao','Geologia Geral','10ª Classe','TECNICA',3,'core'),
('tec_perfuracao_producao','Electrotecnia','10ª Classe','TECNICA',4,'core'),
('tec_perfuracao_producao','Pesquisa e Prospecção','10ª Classe','TECNICA',4,'core'),
('tec_perfuracao_producao','Estudo de Jazidas','11ª Classe','TECNICA',4,'core'),
('tec_perfuracao_producao','Tecnologia de Perfuração','11ª Classe','TECNICA',5,'core'),
('tec_perfuracao_producao','Tecnologia de Produção','11ª Classe','TECNICA',5,'core'),
('tec_perfuracao_producao','Tecnologia Geral de Máquinas','11ª Classe','TECNICA',4,'core'),
('tec_perfuracao_producao','Tecnologia de Perfuração','12ª Classe','TECNICA',4,'core'),
('tec_perfuracao_producao','Tecnologia de Produção','12ª Classe','TECNICA',4,'core'),
('tec_perfuracao_producao','Instrumentação e Controle','12ª Classe','TECNICA',3,'core'),
('tec_perfuracao_producao','Segurança e Meio Ambiente','12ª Classe','TECNICA',3,'core'),
('tec_perfuracao_producao','Inglês Técnico','12ª Classe','TECNICA',3,'core'),
('tec_perfuracao_producao','Trabalhos de Campo','13ª Classe','TECNICA',8,'core'),
('tec_perfuracao_producao','Projecto Tecnológico','13ª Classe','TECNICA',8,'core'),
('tec_perfuracao_producao','Estágio Curricular','13ª Classe','TECNICA',20,'core'),

-- Técnico de Minas
('tec_minas','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_minas','Introdução à Indústria de Minas','10ª Classe','TECNICA',2,'core'),
('tec_minas','Geologia Geral','10ª Classe','TECNICA',2,'core'),
('tec_minas','Mineralogia e Cristalografia','10ª Classe','TECNICA',2,'core'),
('tec_minas','Tecnologia Mineira','10ª Classe','TECNICA',2,'core'),
('tec_minas','Técnicas de Prospecção','10ª Classe','TECNICA',2,'core'),
('tec_minas','Preparação de Minérios','11ª Classe','TECNICA',3,'core'),
('tec_minas','Tecnologia Mineira','11ª Classe','TECNICA',2,'core'),
('tec_minas','Geologia Geral','11ª Classe','TECNICA',3,'core'),
('tec_minas','Tecnologia Mineira','12ª Classe','TECNICA',3,'core'),
('tec_minas','Preparação de Minérios','12ª Classe','TECNICA',3,'core'),
('tec_minas','Jazigos Minerais','12ª Classe','TECNICA',3,'core'),
('tec_minas','Topografia','12ª Classe','TECNICA',3,'core'),
('tec_minas','Instrumentação e Controlo','12ª Classe','TECNICA',4,'core'),
('tec_minas','Trabalhos de Campo','13ª Classe','TECNICA',4,'core'),
('tec_minas','Projecto Tecnológico','13ª Classe','TECNICA',8,'core'),
('tec_minas','Estágio Curricular','13ª Classe','TECNICA',16,'core'),

-- Produção em Metalomecânica
('tec_producao_metalomecanica','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_producao_metalomecanica','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_producao_metalomecanica','Química','10ª Classe','CIENTIFICA',3,'core'),
('tec_producao_metalomecanica','Desenho de Construções Mecânicas','10ª Classe','TECNICA',2,'core'),
('tec_producao_metalomecanica','Tecnologia Mecânica','10ª Classe','TECNICA',2,'core'),
('tec_producao_metalomecanica','Práticas Oficinais','10ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Elementos de Máquinas','11ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Tecnologia Mecânica','11ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Desenho de Construções Mecânicas','11ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Práticas Oficinais','11ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Elementos de Máquinas','12ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Tecnologias de Comando','12ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Controlo da Qualidade','12ª Classe','TECNICA',3,'core'),
('tec_producao_metalomecanica','Práticas Oficinais','12ª Classe','TECNICA',4,'core'),
('tec_producao_metalomecanica','Projecto Tecnológico','13ª Classe','TECNICA',8,'core'),
('tec_producao_metalomecanica','Estágio Curricular','13ª Classe','TECNICA',20,'core'),

-- Técnico de Informática (Hardware)
('tec_informatica','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_informatica','Física','10ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Química','10ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Electrotecnia','10ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Empreendedorismo','10ª Classe','TECNICA',2,'core'),
('tec_informatica','Técnicas e Linguagens de Programação','10ª Classe','TECNICA',3,'core'),
('tec_informatica','Sistemas de Exploração e Arquitectura de Computadores','10ª Classe','TECNICA',2,'core'),
('tec_informatica','Tecnologias de Informação e de Comunicação','10ª Classe','TECNICA',4,'core'),
('tec_informatica','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_informatica','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_informatica','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_informatica','Física','11ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Química','11ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Electrotecnia','11ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Empreendedorismo','11ª Classe','TECNICA',2,'core'),
('tec_informatica','Desenho Técnico','11ª Classe','TECNICA',3,'core'),
('tec_informatica','Técnicas e Linguagens de Programação','11ª Classe','TECNICA',3,'core'),
('tec_informatica','Sistemas de Exploração e Arquitectura de Computadores','11ª Classe','TECNICA',4,'core'),
('tec_informatica','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_informatica','Física','12ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Organização e Gestão Industrial','12ª Classe','CIENTIFICA',2,'core'),
('tec_informatica','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_informatica','Técnicas e Linguagens de Programação','12ª Classe','TECNICA',6,'core'),
('tec_informatica','Técnicas de Reparação de Equipamentos Informáticos','12ª Classe','TECNICA',7,'core'),
('tec_informatica','Sistemas de Exploração e Arquitectura de Computadores','12ª Classe','TECNICA',4,'core'),
('tec_informatica','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_informatica','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_informatica','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Gestão de Sistemas Informáticos
('tec_gestao_sistemas','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_gestao_sistemas','Língua Inglesa ou Francesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_gestao_sistemas','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_gestao_sistemas','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_gestao_sistemas','Matemática','10ª Classe','CIENTIFICA',5,'core'),
('tec_gestao_sistemas','Física','10ª Classe','CIENTIFICA',2,'core'),
('tec_gestao_sistemas','Química','10ª Classe','CIENTIFICA',2,'core'),
('tec_gestao_sistemas','Empreendedorismo','10ª Classe','TECNICA',2,'core'),
('tec_gestao_sistemas','Desenho Técnico','10ª Classe','TECNICA',3,'core'),
('tec_gestao_sistemas','Técnicas e Linguagens de Programação','10ª Classe','TECNICA',4,'core'),
('tec_gestao_sistemas','Sistemas de Exploração e Arquitectura de Computadores','10ª Classe','TECNICA',4,'core'),
('tec_gestao_sistemas','Tecnologias de Informação e de Comunicação','10ª Classe','TECNICA',3,'core'),
('tec_gestao_sistemas','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_gestao_sistemas','Língua Inglesa ou Francesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_gestao_sistemas','Formação de Atitudes Integradoras','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_gestao_sistemas','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_gestao_sistemas','Matemática','11ª Classe','CIENTIFICA',4,'core'),
('tec_gestao_sistemas','Física','11ª Classe','CIENTIFICA',2,'core'),
('tec_gestao_sistemas','Química','11ª Classe','CIENTIFICA',2,'core'),
('tec_gestao_sistemas','Empreendedorismo','11ª Classe','TECNICA',2,'core'),
('tec_gestao_sistemas','Técnicas e Linguagens de Programação','11ª Classe','TECNICA',4,'core'),
('tec_gestao_sistemas','Sistemas de Exploração e Arquitectura de Computadores','11ª Classe','TECNICA',3,'core'),
('tec_gestao_sistemas','Tecnologias de Informação e de Comunicação','11ª Classe','TECNICA',2,'core'),
('tec_gestao_sistemas','Matemática','12ª Classe','CIENTIFICA',5,'core'),
('tec_gestao_sistemas','Física','12ª Classe','CIENTIFICA',2,'core'),
('tec_gestao_sistemas','Organização e Gestão de Empresas','12ª Classe','CIENTIFICA',4,'core'),
('tec_gestao_sistemas','Empreendedorismo','12ª Classe','TECNICA',2,'core'),
('tec_gestao_sistemas','Técnicas e Linguagens de Programação','12ª Classe','TECNICA',6,'core'),
('tec_gestao_sistemas','Redes Informáticas','12ª Classe','TECNICA',6,'core'),
('tec_gestao_sistemas','Tecnologias de Informação e de Comunicação','12ª Classe','TECNICA',3,'core'),
('tec_gestao_sistemas','Projecto Tecnológico','12ª Classe','TECNICA',4,'projeto'),
('tec_gestao_sistemas','Projecto Tecnológico','13ª Classe','TECNICA',8,'projeto'),
('tec_gestao_sistemas','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Análises Clínicas
('tec_saude_analises','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_analises','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_analises','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_analises','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_analises','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_analises','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_analises','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_analises','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_analises','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_analises','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Anatomia e Fisiologia Humana','11ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Microbiologia Clínica I','11ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Hematologia I','11ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Imunologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_analises','Urinologia','11ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Coprologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_analises','Práticas de Análises Clínicas','11ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Psicologia Geral','12ª Classe','CIENTIFICA',3,'core'),
('tec_saude_analises','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',2,'core'),
('tec_saude_analises','Microbiologia Clínica II','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Hematologia II','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Imunohematologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Microbiologia de Água e Alimentos','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Bioquímica','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Química Clínica','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Parasitologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_analises','Práticas de Análises Clínicas','12ª Classe','TECNICA',4,'core'),
('tec_saude_analises','Gestão em Análises Clínicas','13ª Classe','TECNICA',4,'core'),
('tec_saude_analises','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_analises','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Enfermagem
('tec_saude_enfermagem','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_enfermagem','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_enfermagem','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_enfermagem','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_enfermagem','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_enfermagem','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_enfermagem','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_enfermagem','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_enfermagem','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_enfermagem','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_enfermagem','Psicologia Geral','11ª Classe','CIENTIFICA',2,'core'),
('tec_saude_enfermagem','Anatomia e Fisiologia Humana','11ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Epidemiologia e Estatística','11ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Enfermagem em Saúde Colectiva','11ª Classe','TECNICA',2,'core'),
('tec_saude_enfermagem','Enfermagem e Patologia Médico-Cirúrgica I','11ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Técnicas de Enfermagem I','11ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Enfermagem em Saúde Mental','12ª Classe','TECNICA',2,'core'),
('tec_saude_enfermagem','Farmacologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Doenças Correntes','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Nutrição e Dietética','12ª Classe','TECNICA',2,'core'),
('tec_saude_enfermagem','Enfermagem e Patologia Médico-Cirúrgica II','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Técnicas de Enfermagem II','12ª Classe','TECNICA',4,'core'),
('tec_saude_enfermagem','Saúde da Mulher','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Saúde da Criança','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Enfermagem em Urgência','12ª Classe','TECNICA',3,'core'),
('tec_saude_enfermagem','Gestão em Enfermagem','13ª Classe','TECNICA',4,'core'),
('tec_saude_enfermagem','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_enfermagem','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Estomatologia
('tec_saude_estomatologia','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_estomatologia','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_estomatologia','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_estomatologia','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_estomatologia','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_estomatologia','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_estomatologia','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_estomatologia','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_estomatologia','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_estomatologia','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_estomatologia','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Psicologia Geral','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_estomatologia','Anatomia e Fisiologia Humana','11ª Classe','TECNICA',2,'core'),
('tec_saude_estomatologia','Anatomia da Cabeça e do Pescoço','11ª Classe','TECNICA',3,'core'),
('tec_saude_estomatologia','Patologia e Semiologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_estomatologia','Microbiologia e Esterilização','11ª Classe','TECNICA',2,'core'),
('tec_saude_estomatologia','Aparelhagem Instrumental','11ª Classe','TECNICA',2,'core'),
('tec_saude_estomatologia','Farmacologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_estomatologia','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',3,'core'),
('tec_saude_estomatologia','Anatomia da Cabeça e do Pescoço','12ª Classe','TECNICA',4,'core'),
('tec_saude_estomatologia','Exodância','12ª Classe','TECNICA',4,'core'),
('tec_saude_estomatologia','Radiologia Dentária','12ª Classe','TECNICA',3,'core'),
('tec_saude_estomatologia','Terapêutica Dentária','12ª Classe','TECNICA',3,'core'),
('tec_saude_estomatologia','Dentística Restauradora','12ª Classe','TECNICA',3,'core'),
('tec_saude_estomatologia','Práticas Estomatologia','12ª Classe','TECNICA',4,'core'),
('tec_saude_estomatologia','Gestão em Estomatologia','13ª Classe','TECNICA',4,'core'),
('tec_saude_estomatologia','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_estomatologia','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Farmácia
('tec_saude_farmacia','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_farmacia','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_farmacia','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_farmacia','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_farmacia','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_farmacia','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_farmacia','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_farmacia','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_farmacia','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_farmacia','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Anatomia e Fisiologia Humana','11ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Patologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_farmacia','Botânica','11ª Classe','TECNICA',2,'core'),
('tec_saude_farmacia','Microparasitologia','11ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Farmacologia I','11ª Classe','TECNICA',2,'core'),
('tec_saude_farmacia','Farmacognosia','11ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Química Analítica','11ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Psicologia Geral','12ª Classe','CIENTIFICA',3,'core'),
('tec_saude_farmacia','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Bromatologia','12ª Classe','TECNICA',2,'core'),
('tec_saude_farmacia','Patologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Farmacologia II','12ª Classe','TECNICA',4,'core'),
('tec_saude_farmacia','Química Farmacêutica','12ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Tecnologia de Produção de Medicamentos','12ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Farmacoterapia','12ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Toxicologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_farmacia','Práticas de Farmácia','12ª Classe','TECNICA',4,'core'),
('tec_saude_farmacia','Gestão em Farmácia','13ª Classe','TECNICA',4,'core'),
('tec_saude_farmacia','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_farmacia','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Fisioterapia
('tec_saude_fisioterapia','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_fisioterapia','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_fisioterapia','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_fisioterapia','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_fisioterapia','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_fisioterapia','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_fisioterapia','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_fisioterapia','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_fisioterapia','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_fisioterapia','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Psicologia Geral','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_fisioterapia','Patologia Geral','11ª Classe','TECNICA',2,'core'),
('tec_saude_fisioterapia','Anatomia e Fisiologia Humana','11ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Estudo do Movimento Humano','11ª Classe','TECNICA',2,'core'),
('tec_saude_fisioterapia','Fisioterapia Neuro-muscular','11ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Fisioterapia Músculo-esquelética','11ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Patologia Específica','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Fisioterapia Cardio-respiratória','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Fisioterapia Neuro-muscular','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Fisioterapia Músculo-esquelética','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Fisioterapia Materno Infantil','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Recursos Fisioterapêuticos','12ª Classe','TECNICA',3,'core'),
('tec_saude_fisioterapia','Ortoprotesia em Fisioterapia','12ª Classe','TECNICA',4,'core'),
('tec_saude_fisioterapia','Prática em Fisioterapia','12ª Classe','TECNICA',4,'core'),
('tec_saude_fisioterapia','Estágio Prático Parcelar','12ª Classe','TECNICA',4,'core'),
('tec_saude_fisioterapia','Gestão em Fisioterapia','13ª Classe','TECNICA',4,'core'),
('tec_saude_fisioterapia','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_fisioterapia','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Nutrição
('tec_saude_nutricao','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_nutricao','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_nutricao','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_nutricao','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_nutricao','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_nutricao','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_nutricao','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_nutricao','Língua Inglesa','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_nutricao','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_nutricao','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Anatomia e Fisiologia Humana','11ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Patologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_nutricao','Farmacologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_nutricao','Nutrição Humana e Comunitária','11ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Dietética Geral e Especial','11ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Psicologia Geral','12ª Classe','CIENTIFICA',3,'core'),
('tec_saude_nutricao','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Patologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Farmacologia','12ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Nutrição Humana e Comunitária','12ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Dietética Geral e Especial','12ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Técnicas Dietéticas','12ª Classe','TECNICA',4,'core'),
('tec_saude_nutricao','Dietética Laboratorial','12ª Classe','TECNICA',4,'core'),
('tec_saude_nutricao','Microbiologia e Higiene dos Alimentos','12ª Classe','TECNICA',3,'core'),
('tec_saude_nutricao','Práticas de Nutrição e Dietética','12ª Classe','TECNICA',4,'core'),
('tec_saude_nutricao','Gestão em Nutrição','13ª Classe','TECNICA',4,'core'),
('tec_saude_nutricao','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_nutricao','Estágio Curricular','13ª Classe','TECNICA',20,'estagio'),

-- Técnico de Radiologia
('tec_saude_radiologia','Língua Portuguesa','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_radiologia','Língua Estrangeira','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_radiologia','Formação de Atitudes Integradoras','10ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_radiologia','Educação Física','10ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_radiologia','Matemática','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Biologia','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Física','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Química Geral','10ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Informática','10ª Classe','CIENTIFICA',2,'core'),
('tec_saude_radiologia','Introdução à Profissão, Ética e Deontologia','10ª Classe','TECNICA',3,'core'),
('tec_saude_radiologia','Anatomia e Fisiologia Humana','10ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Língua Portuguesa','11ª Classe','SOCIO_CULTURAL',3,'core'),
('tec_saude_radiologia','Língua Estrangeira','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_radiologia','Educação Física','11ª Classe','SOCIO_CULTURAL',2,'core'),
('tec_saude_radiologia','Matemática','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Biologia','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Química Orgânica','11ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Física das Radiações','11ª Classe','TECNICA',3,'core'),
('tec_saude_radiologia','Anatomia Radiológica I','11ª Classe','TECNICA',3,'core'),
('tec_saude_radiologia','Processamento Radiológico','11ª Classe','TECNICA',3,'core'),
('tec_saude_radiologia','Enfermagem em Radiologia','11ª Classe','TECNICA',2,'core'),
('tec_saude_radiologia','Métodos e Técnicas em Radiologia I','11ª Classe','TECNICA',3,'core'),
('tec_saude_radiologia','Patologia Radiológica I','11ª Classe','TECNICA',2,'core'),
('tec_saude_radiologia','Psicologia Geral','12ª Classe','CIENTIFICA',3,'core'),
('tec_saude_radiologia','Informação, Educação e Comunicação - IEC','12ª Classe','TECNICA',3,'core'),
('tec_saude_radiologia','Anatomia Radiológica II','12ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Métodos e Técnicas em Radiologia II','12ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Protecção e Segurança Radiológica','12ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Patologia Radiológica II','12ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Métodos e Técnicas Especiais em Radiologia','12ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Práticas de Radiologia','12ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Gestão em Radiologia','13ª Classe','TECNICA',4,'core'),
('tec_saude_radiologia','Projecto Tecnológico','13ª Classe','TECNICA',4,'projeto'),
('tec_saude_radiologia','Estágio Curricular','13ª Classe','TECNICA',20,'estagio')
ON CONFLICT (preset_id, name, grade_level) DO UPDATE SET
component = EXCLUDED.component,
weekly_hours = EXCLUDED.weekly_hours,
subject_type = EXCLUDED.subject_type;

COMMIT;
