import "server-only";

import { supabaseServerRole } from "@/lib/supabaseServerRole";
import type { Database, Json } from "~types/supabase";

type Snapshot = Record<string, unknown>;

/**
 * Operational receipts are generated by the authorized SECURITY DEFINER RPC,
 * but RLS intentionally has no UPDATE policy for documentos_emitidos.
 * This server-only, tenant-scoped write enriches a receipt AFTER successful
 * issuance; it must never issue receipts or alter their immutable identifiers.
 */
export async function enrichOperationalReceiptSnapshot({
  escolaId,
  docId,
  alunoId,
  extraSnapshot,
}: {
  escolaId: string;
  docId: string;
  alunoId: string;
  extraSnapshot: Snapshot;
}): Promise<void> {
  const admin = supabaseServerRole<Database>();
  const { data: doc, error: fetchError } = await admin
    .from("documentos_emitidos")
    .select("id, aluno_id, created_at, dados_snapshot")
    .eq("id", docId)
    .eq("escola_id", escolaId)
    .eq("aluno_id", alunoId)
    .eq("tipo", "recibo")
    .is("revoked_at", null)
    .maybeSingle();

  if (fetchError || !doc) {
    throw new Error("RECIBO_ENRICHMENT_DOCUMENT_NOT_FOUND");
  }

  // Historic receipts are evidence. Replays must not silently recompose them
  // from new client input; deliberate historic repair is a separate audit action.
  const createdAt = Date.parse(doc.created_at);
  if (!Number.isFinite(createdAt) || Date.now() - createdAt > 60 * 60 * 1000) return;

  const existing = doc.dados_snapshot && typeof doc.dados_snapshot === "object" && !Array.isArray(doc.dados_snapshot)
    ? doc.dados_snapshot as Snapshot
    : {};

  // Preserve an already enriched document on idempotent replays.
  if (Array.isArray(existing.itens_pagamento) && existing.itens_pagamento.length > 0) return;

  const allowedKeys = ["tipo_comprovativo", "itens_pagamento", "referencia", "valor_pago", "metodo", "data_pagamento"] as const;
  const additions: Snapshot = {};
  for (const key of allowedKeys) {
    if (extraSnapshot[key] !== undefined) additions[key] = extraSnapshot[key];
  }

  const { data: updated, error: updateError } = await admin
    .from("documentos_emitidos")
    .update({ dados_snapshot: { ...existing, ...additions } as Json })
    .eq("id", docId)
    .eq("escola_id", escolaId)
    .eq("aluno_id", alunoId)
    .eq("tipo", "recibo")
    .is("revoked_at", null)
    .select("id, dados_snapshot")
    .maybeSingle();

  if (updateError || !updated) {
    throw new Error("RECIBO_ENRICHMENT_WRITE_FAILED");
  }
  const snapshot = updated.dados_snapshot;
  const persistedItems = snapshot && typeof snapshot === "object" && !Array.isArray(snapshot)
    ? (snapshot as Snapshot).itens_pagamento
    : null;
  if (Array.isArray(additions.itens_pagamento) && additions.itens_pagamento.length > 0 &&
      (!Array.isArray(persistedItems) || persistedItems.length !== additions.itens_pagamento.length)) {
    throw new Error("RECIBO_ENRICHMENT_NOT_PERSISTED");
  }
}
