import { Document, Page, StyleSheet, Text, View, renderToBuffer, type DocumentProps } from "@react-pdf/renderer";

const styles = StyleSheet.create({ page: { padding: 36, fontSize: 10, color: "#172033" }, title: { fontSize: 18, fontWeight: 700, marginBottom: 4 }, subtitle: { fontSize: 10, color: "#64748b", marginBottom: 18 }, section: { marginBottom: 14, padding: 12, border: "1 solid #e2e8f0", borderRadius: 6 }, sectionTitle: { fontSize: 11, fontWeight: 700, marginBottom: 8, color: "#0f5132" }, row: { flexDirection: "row", marginBottom: 5 }, label: { width: 110, color: "#64748b" }, value: { flex: 1 }, metricGrid: { flexDirection: "row", gap: 8 }, metric: { flex: 1, padding: 9, backgroundColor: "#f8fafc", borderRadius: 5 }, metricValue: { fontSize: 16, fontWeight: 700 }, metricLabel: { fontSize: 8, color: "#64748b", marginTop: 3 }, item: { padding: 7, borderBottom: "1 solid #e2e8f0" }, small: { fontSize: 8, color: "#64748b" }, footer: { marginTop: 18, fontSize: 8, color: "#94a3b8" } });

function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat("pt-PT", { dateStyle: "long" }).format(new Date(`${value}T12:00:00`)) : "-"; }
function time(value?: string | null) { return value ? String(value).slice(0, 5) : "-"; }

export async function renderAulaRelatorioPdf(report: any) {
  const { aula, turma, disciplina, professor, attendance, attendanceRows, plano, atividades } = report;
  const element = <Document><Page size="A4" style={styles.page}>
    <Text style={styles.title}>Relatório da aula</Text>
    <Text style={styles.subtitle}>Registo operacional e pedagógico da ocorrência</Text>
    <View style={styles.section}><Text style={styles.sectionTitle}>Identificação</Text><View style={styles.row}><Text style={styles.label}>Turma</Text><Text style={styles.value}>{turma?.nome ?? "-"}</Text></View><View style={styles.row}><Text style={styles.label}>Disciplina</Text><Text style={styles.value}>{disciplina?.nome ?? "-"}</Text></View><View style={styles.row}><Text style={styles.label}>Professor</Text><Text style={styles.value}>{professor?.nome_completo ?? "-"}</Text></View><View style={styles.row}><Text style={styles.label}>Data</Text><Text style={styles.value}>{formatDate(aula.data)}</Text></View><View style={styles.row}><Text style={styles.label}>Horário</Text><Text style={styles.value}>{time(aula.inicio_previsto)} - {time(aula.fim_previsto)}</Text></View><View style={styles.row}><Text style={styles.label}>Estado</Text><Text style={styles.value}>{aula.status}</Text></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Frequência</Text><View style={styles.metricGrid}><View style={styles.metric}><Text style={styles.metricValue}>{attendance.presentes}</Text><Text style={styles.metricLabel}>Presentes</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{attendance.faltas}</Text><Text style={styles.metricLabel}>Faltas</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{attendance.atrasos}</Text><Text style={styles.metricLabel}>Atrasos</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{attendance.total}</Text><Text style={styles.metricLabel}>Registos</Text></View></View></View>
    {attendanceRows.length > 0 && <View style={styles.section}><Text style={styles.sectionTitle}>Frequência nominal</Text>{attendanceRows.map((row: any) => <View key={row.matricula_id} style={styles.item}><Text>{row.aluno?.nome_completo ?? row.aluno?.nome ?? "Aluno não identificado"}</Text><Text style={styles.small}>{row.status}{row.aluno?.numero_processo ? ` - ${row.aluno.numero_processo}` : ""}</Text></View>)}</View>}
    <View style={styles.section}><Text style={styles.sectionTitle}>Registo do professor</Text><Text style={styles.small}>Conteúdo</Text><Text>{aula.conteudo ?? "Não informado."}</Text><Text style={styles.small}>Resumo</Text><Text>{aula.resumo ?? "Não informado."}</Text><Text style={styles.small}>Observações</Text><Text>{aula.observacoes ?? "Não informado."}</Text></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Plano de aula</Text>{plano ? <><View style={styles.row}><Text style={styles.label}>Tema</Text><Text style={styles.value}>{plano.tema}</Text></View><View style={styles.row}><Text style={styles.label}>Estado</Text><Text style={styles.value}>{plano.status}</Text></View><Text>{plano.objetivos ?? "Objetivos não informados."}</Text></> : <Text>Não associado a esta ocorrência.</Text>}</View>
    {atividades.length > 0 && <View style={styles.section}><Text style={styles.sectionTitle}>Atividades</Text>{atividades.map((item: any) => <View key={item.id} style={styles.item}><Text>{item.titulo}</Text><Text style={styles.small}>{item.status ?? "Sem estado"}{item.nota_maxima ? ` - ${item.nota_maxima} pontos` : ""}</Text></View>)}</View>}
    <Text style={styles.footer}>Documento gerado pelo KLASSE em {new Date().toLocaleString("pt-PT")}</Text>
  </Page></Document>;
  return renderToBuffer(element as React.ReactElement<DocumentProps>);
}
