BEGIN;

REVOKE EXECUTE ON FUNCTION
  public.refresh_mv_admin_dashboard_counts(),
  public.refresh_mv_admin_matriculas_por_mes(),
  public.refresh_mv_admissoes_counts_por_status(),
  public.refresh_mv_escola_info(),
  public.refresh_mv_financeiro_dashboard(),
  public.refresh_mv_financeiro_escola_dia(),
  public.refresh_mv_financeiro_inadimplencia_top(),
  public.refresh_mv_financeiro_kpis_mes(),
  public.refresh_mv_financeiro_missing_pricing_count(),
  public.refresh_mv_financeiro_propinas_mensal_escola(),
  public.refresh_mv_financeiro_propinas_por_turma(),
  public.refresh_mv_financeiro_sidebar_badges(),
  public.refresh_mv_formacao_cohorts_lotacao(),
  public.refresh_mv_formacao_inadimplencia_resumo(),
  public.refresh_mv_formacao_margem_por_edicao(),
  public.refresh_mv_freq_por_turma_dia(),
  public.refresh_mv_pagamentos_status(),
  public.refresh_mv_professor_pendencias(),
  public.refresh_mv_radar_inadimplencia(),
  public.refresh_mv_relatorio_financeiro_escolar_capitacao_mensal(),
  public.refresh_mv_relatorio_financeiro_escolar_fluxo_mensal(),
  public.refresh_mv_relatorio_financeiro_escolar_inadimplencia_classe(),
  public.refresh_mv_secretaria_alunos_resumo(),
  public.refresh_mv_secretaria_dashboard_counts(),
  public.refresh_mv_secretaria_matriculas_status(),
  public.refresh_mv_super_admin_audit_metrics(),
  public.refresh_mv_super_admin_escola_metrics(),
  public.refresh_mv_top_cursos_media(),
  public.refresh_mv_top_turmas_hoje()
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION
  public.refresh_mv_admin_dashboard_counts(),
  public.refresh_mv_admin_matriculas_por_mes(),
  public.refresh_mv_admissoes_counts_por_status(),
  public.refresh_mv_escola_info(),
  public.refresh_mv_financeiro_dashboard(),
  public.refresh_mv_financeiro_escola_dia(),
  public.refresh_mv_financeiro_inadimplencia_top(),
  public.refresh_mv_financeiro_kpis_mes(),
  public.refresh_mv_financeiro_missing_pricing_count(),
  public.refresh_mv_financeiro_propinas_mensal_escola(),
  public.refresh_mv_financeiro_propinas_por_turma(),
  public.refresh_mv_financeiro_sidebar_badges(),
  public.refresh_mv_formacao_cohorts_lotacao(),
  public.refresh_mv_formacao_inadimplencia_resumo(),
  public.refresh_mv_formacao_margem_por_edicao(),
  public.refresh_mv_freq_por_turma_dia(),
  public.refresh_mv_pagamentos_status(),
  public.refresh_mv_professor_pendencias(),
  public.refresh_mv_radar_inadimplencia(),
  public.refresh_mv_relatorio_financeiro_escolar_capitacao_mensal(),
  public.refresh_mv_relatorio_financeiro_escolar_fluxo_mensal(),
  public.refresh_mv_relatorio_financeiro_escolar_inadimplencia_classe(),
  public.refresh_mv_secretaria_alunos_resumo(),
  public.refresh_mv_secretaria_dashboard_counts(),
  public.refresh_mv_secretaria_matriculas_status(),
  public.refresh_mv_super_admin_audit_metrics(),
  public.refresh_mv_super_admin_escola_metrics(),
  public.refresh_mv_top_cursos_media(),
  public.refresh_mv_top_turmas_hoje()
TO service_role;

COMMIT;
